name: gane
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.10+61

environment:
  #sdk: '>=2.19.6 <3.0.0'
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.9
  convert: ^3.1.0
  shared_preferences: ^2.0.7
  http: ^1.1.0
  oktoast: ^3.0.0
  date_utils: ^0.2.0
  fluttertoast: ^8.0.7
  auto_size_text: ^3.0.0-nullsafety.0
  rxdart: ^0.27.0
  open_settings: ^2.0.1
  permission_handler: ^11.0.1
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.2
  email_validator: ^3.0.0
  keyboard_actions: ^4.2.0
  animated_widgets: ^1.0.6
  spring_button: ^2.0.0
  pull_to_refresh: ^2.0.0
  modal_bottom_sheet: ^2.0.0
  lottie: ^2.7.0
  webview_flutter: ^4.5.0
  #flutter_animated_dialog: ^2.0.1
  material_dialogs: ^1.1.4
  cached_network_image: ^3.2.3
  encrypt: ^5.0.0
  crypto: ^3.0.0
  image_cropper: ^5.0.0
  image_cropper_platform_interface: ^5.0.0
  js: ^0.6.7
  image_picker: ^1.0.8
  flutter_bloc: ^8.1.6
  path_provider: ^2.0.15
  shimmer_animation: ^2.1.0+1
  bot_toast: ^4.0.1
  provider: ^6.0.5
  argon_buttons_flutter_fix: ^1.1.3
  extended_masked_text: ^2.3.1
  flutter_masked_text2: ^0.9.1
  animate_do: ^3.0.2
  pin_code_fields: ^8.0.1
  transition: ^2.0.2
  location: ^5.0.3
  flutter_staggered_grid_view: ^0.4.0
  floating_bottom_navigation_bar: ^1.5.2
  motion_toast: ^2.10.0
  another_flushbar: ^1.12.30
  top_snackbar_flutter: ^3.1.0
  flutter_svg: ^2.0.5
  #liquid_progress_indicator: ^0.4.0
  liquid_progress_indicator_v2: ^0.5.0
  smooth_page_indicator: ^1.2.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_page_view_indicator: ^0.0.5
  expandable_page_view: ^1.0.6
  intl: ^0.17.0
  bordered_text: ^2.0.0
  video_player: ^2.1.14
  percent_indicator: ^4.2.3
  page_transition: ^2.0.9
  flutter_staggered_animations: ^1.0.0
  route_transitions: ^2.0.1
  flutter_slidable: ^3.1.1
  flutter_switch: ^0.3.2
  animated_counter: ^1.0.0
  flutter_local_notifications: ^17.2.1+2
  #firebase_messaging: ^14.2.1
  #firebase_core: ^2.4.1
  #firebase_core_platform_interface: ^4.5.1
  firebase_messaging: ^14.7.10
  firebase_core: ^2.24.2
  firebase_core_platform_interface: ^5.1.0
  flip_card: ^0.7.0
  audioplayers: ^5.1.0
  timeago: ^3.0.0
  material_design_icons_flutter: ^7.0.7296
  rflutter_alert: ^2.0.4
  badges: ^3.1.2
  timer_count_down: ^2.2.0
  flutter_archive: ^6.0.3
  flutter_widget_from_html_core: ^0.15.1
  mime_type: ^1.0.0
  vimeo_player_flutter: ^0.1.0
  flutter_lints: ^4.0.0
  concentric_transition: ^1.0.1
  stylish_bottom_bar: ^1.1.0
  animated_flip_counter: ^0.3.4
  connectivity_plus: ^5.0.2
  sleek_circular_slider: ^2.0.1
  #device_information: ^0.0.4
  navigation_history_observer: ^1.1.0
  airplane_mode_checker: ^2.0.0
  clipboard: ^0.1.3
  syncfusion_flutter_barcodes: ^20.4.50
  flutter_inappwebview: ^6.0.0
  flutter_share: ^2.0.0
  slider_captcha: ^1.0.0
  flutter_html: ^3.0.0-beta.2
  #sms_autofill: ^2.4.0
  flutter_barcode_scanner: ^2.0.0
  step_progress_indicator: ^1.0.2
  file: ^7.0.0
  chewie: ^1.7.5
  win32: ^5.5.4

  fwfh_text_style: ^2.22.8+1
  flutter_math_fork: ^0.7.2
  platform: ^3.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2


dev_dependencies:
  #flutter_test:
   # sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:

    - assets/
    - assets/images/
    - assets/images/Games/
    - assets/images/Games/Run/
    - assets/images/Games/Run/dino/
    - assets/images/Games/Run/cacti/
    - assets/images/Games/Run/ptera/
    - assets/images/Games/Bird/
    - assets/images/Games/Flip/
    - assets/images/Games/PopBubbles/
    - assets/images/Games/PacM/
    - assets/images/Games/Hangman/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:

  fonts:
    - family: MontserratBold
      fonts:
        - asset: fonts/MontserratBold.ttf
    - family: MontserratBlack
      fonts:
        - asset: fonts/MontserratBlack.ttf
    - family: MontserratMedium
      fonts:
        - asset: fonts/MontserratMedium.ttf
    - family: MontserratRegular
      fonts:
        - asset: fonts/MontserratRegular.ttf
    - family: MontserratSemiBold
      fonts:
        - asset: fonts/MontserratSemiBold.ttf
    - family: volkswagen
      fonts:
        - asset: fonts/volkswagen.ttf
    - family: FredokaBold
      fonts:
        - asset: fonts/Fredoka-Bold.ttf
    - family: FredokaMedium
      fonts:
        - asset: fonts/Fredoka-Medium.ttf
    - family: FredokaRegular
      fonts:
        - asset: fonts/Fredoka-Regular.ttf
    - family: FredokaSemiBold
      fonts:
        - asset: fonts/Fredoka-SemiBold.ttf
    - family: RobotoBold
      fonts:
        - asset: fonts/Roboto-Bold.ttf
    - family: RobotoMedium
      fonts:
        - asset: fonts/Roboto-Medium.ttf
    - family: RobotoRegular
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: RobotoBoldItalic
      fonts:
        - asset: fonts/Roboto-BoldItalic.ttf
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf


  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
